export const hotelTypes = [

    "Hotel",
    "Resort",
    "Guest House",
    "Apartment",
    "Villa",
    "Motel",
    "Hostel",
    "Inn",
    "Bed & Breakfast",
    "Boutique Hotel",
    "Cottage",
    "Bungalow",
    "Cabin",
    "Camp",
    "Riad",
    "Pension",
    "Ryokan",
    "Palace",
    "Castle",
    "Manor",
    "Eco Hotel",
    "Farm Stay",
    "Boat",
    "Tent",
    "Treehouse",
    "Capsule Hotel",
    "Love Hotel",
    "Minsu",
    "Aparthotel",
    "Chalet",




]


export const hotelFacilities = [

    "Free Wi-Fi",
    "Free parking",
    "Airport shuttle",
    "Swimming pool",
    "Spa",
    "Fitness center",
    "Bar",
    "Breakfast",
    "Restaurant",
    "Non-smoking rooms",
    "Pet friendly",
    "Family rooms",
    "Room service",
    "Facilities for disabled guests",
    "24-hour front desk",
    "Elevator",
    "Air conditioning",
    "Heating",
    "Private beach area",
    "Balcony",
    "Terrace",
    "Garden",
    "BBQ facilities",
    "Kitchen",
    "Kitchenette",
    "Microwave",
    "Refrigerator",
    "Coffee machine",
    "Electric kettle",
    "Dishwasher",
    "Oven",
    "Stovetop",
    "Toaster",
    "Kitchenware",
    "Dining area",
    "Dining table",
    "High chair",
    "Children's play area",
    "Board games",
    "Books, DVDs, music for children",
]